[tool.poetry]
name = "ai-spider"
version = "0.2.0"
description = "ai-worker coordination hub and inference endpoint provider"
authors = ["erik aronesty <erik@q32.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
fastapi = "^0.103.1"
websockets = "^11.0.3"
python-dotenv = "^1.0.0"
sse-starlette = "^1.6.5"
uvicorn = "^0.23.2"
itsdangerous = "^2.1.2"
httpx = "*"
python-multipart = "^0.0.6"
boto3 = "^1.28.56"
boto3-stubs = {extras = ["essential"], version = "^1.28.56"}
gunicorn = "^21.2.0"
notanorm = "^3.9.1"
pymysql = "^1.1.0"
nostr = { git = "git@github.com:jeffthibault/python-nostr.git", branch = "main" }

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
ruff = "^0.0.288"
pytest-asyncio = "^0.21.1"
ai-worker = {git = "ssh://git@github.com/ArcadeLabsInc/ai-worker.git"}
httpx-sse = "^0.3.1"
moto = {extras = ["s3"], version = "^4.2.4"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
